# VeriPay Configuration File

# Telegram Bot Configuration
telegram:
  waiter_bot_token: "8450018011:AAHbrKSnGqDLb-t6WAI74RbjN8A7OZNQSSc"
  admin_bot_token: "8450018011:AAHbrKSnGqDLb-t6WAI74RbjN8A7OZNQSSc"
  webhook_url: "https://your-domain.com/webhook"
  admin_user_ids: ["123456789"]  # List of admin Telegram user IDs

# Database Configuration
database:
  url: "sqlite:///lean_veripay.db"
  pool_size: 5
  max_overflow: 10
  echo: false

# AI & OCR Configuration
ai:
  # OCR Settings
  ocr_engine: "tesseract"  # Options: tesseract, easyocr, google_vision
  tesseract_path: "/usr/local/bin/tesseract"
  confidence_threshold: 0.7
  
  # Fraud Detection
  fraud_detection:
    enabled: true
    model_path: "models/fraud_detector.h5"
    confidence_threshold: 0.8
    check_exif: true
    check_noise: true
    check_fonts: true

# Bank API Configuration
banks:
  cbe:
    name: "Commercial Bank of Ethiopia"
    api_url: "https://api.cbe.com.et"
    api_key: "YOUR_CBE_API_KEY"
    verification_url: "https://cbe.com.et/verify"
    enabled: true
    
  telebirr:
    name: "Telebirr"
    api_url: "https://api.telebirr.et"
    api_key: "YOUR_TELEBIRR_API_KEY"
    verification_url: "https://telebirr.et/verify"
    enabled: true
    
  dashen:
    name: "Dashen Bank"
    api_url: "https://api.dashenbank.com"
    api_key: "YOUR_DASHEN_API_KEY"
    verification_url: "https://dashenbank.com/verify"
    enabled: true

# Audit & Reporting
audit:
  reconciliation_interval_days: 3
  report_format: "pdf"  # Options: pdf, excel, csv
  auto_generate_reports: true
  report_retention_days: 90

# File Storage
storage:
  upload_path: "./uploads"
  max_file_size_mb: 10
  allowed_extensions: ["jpg", "jpeg", "png", "pdf"]
  backup_enabled: true
  backup_path: "./backups"

# Logging
logging:
  level: "INFO"
  file: "logs/veripay.log"
  max_size_mb: 100
  backup_count: 5
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"

# Security
security:
  encryption_key: "YOUR_ENCRYPTION_KEY"
  session_timeout_minutes: 30
  max_login_attempts: 5
  password_min_length: 8

# Performance
performance:
  max_concurrent_verifications: 10
  verification_timeout_seconds: 30
  cache_enabled: true
  cache_ttl_seconds: 3600

# Monitoring
monitoring:
  health_check_enabled: true
  metrics_enabled: true
  alert_email: "admin@veripay.et"
  alert_telegram_chat_id: "YOUR_ALERT_CHAT_ID"

# Development
development:
  debug: false
  test_mode: false
  mock_bank_apis: false
  sample_data_enabled: false 