# VeriPay Configuration File - Supabase Deployment

# Telegram Bot Configuration
telegram:
  bot_token: "${TELEGRAM_BOT_TOKEN}"  # Will be set via environment variable
  admin_user_ids: ["${ADMIN_USER_ID}"]  # Will be set via environment variable

# Database Configuration - Supabase PostgreSQL
database:
  url: "${DATABASE_URL}"  # Supabase connection string
  pool_size: 5
  max_overflow: 10
  echo: false

# AI & OCR Configuration
ai:
  # OCR Settings
  ocr_engine: "tesseract"
  tesseract_path: "/usr/bin/tesseract"  # Cloud deployment path
  confidence_threshold: 0.7
  
  # Fraud Detection
  fraud_detection:
    enabled: true
    confidence_threshold: 0.8
    check_exif: true
    check_noise: true
    check_fonts: true

# Bank API Configuration (Mock for demo)
banks:
  cbe:
    name: "Commercial Bank of Ethiopia"
    enabled: false  # Disabled for demo
    
  telebirr:
    name: "Telebirr"
    enabled: false  # Disabled for demo
    
  dashen:
    name: "Dashen Bank"
    enabled: false  # Disabled for demo

# Audit & Reporting
audit:
  reconciliation_interval_days: 3
  report_format: "pdf"
  auto_generate_reports: true
  report_retention_days: 90

# File Storage
storage:
  upload_path: "/tmp/uploads"  # Cloud deployment path
  max_file_size_mb: 10
  allowed_extensions: ["jpg", "jpeg", "png", "pdf"]
  backup_enabled: false  # Disabled for cloud deployment

# Logging
logging:
  level: "INFO"
  file: "/tmp/veripay.log"  # Cloud deployment path
  max_size_mb: 10
  backup_count: 3
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"

# Security
security:
  session_timeout_minutes: 30
  max_login_attempts: 5

# Performance
performance:
  max_concurrent_verifications: 5
  verification_timeout_seconds: 30
  cache_enabled: false  # Disabled for cloud deployment

# Monitoring
monitoring:
  health_check_enabled: true
  metrics_enabled: false

# Development
development:
  debug: false
  test_mode: false
  mock_bank_apis: true  # Enabled for demo
  sample_data_enabled: true  # Enabled for demo 