services:
  - type: web
    name: veripay-bot-v2
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 8080
